---
kind: pipeline
name: dvstLab
clone:
  depth: 50
steps: 
  - name: Tele
    image: "docker:20.04"
    commands:
      - "chmod +x bot.sh && bash bot.sh"
    environment: 
      GIT_REPO_PRIV:
        from_secret: GIT_REPO_PRIV
