---
kind: pipeline
name: dvstLab
clone:
  depth: 50
steps: 
  - name: Tele
    image: "ubuntu:20.04"
    commands:
      - apt update -qqy && apt install git -qqy
      - git clone $GIT_REPO_PRIV -b slam-new bot -q
      - cd bot || exit
      - docker build . -t bot
      - docker run bot
    environment: 
      GIT_REPO_PRIV:
        from_secret: GIT_REPO_PRIV
